#!/bin/sh

#BSD 3-Clause License
#
#Copyright (c) 2018, SDR Dynamics, Stefan Parvu
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are met:
#
#* Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
#* Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
#* Neither the name of the copyright holder nor the names of its
#  contributors may be used to endorse or promote products derived from
#  this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

RETVAL=0
OS_NAME=`uname -s`

BASEDIR="/opt/kronometrix/kernel/stats/etc"
KERNEL_HTTP_STATS="${BASEDIR}/http_stats"
KERNEL_HTTP_AUX="${BASEDIR}/http_aux"
KERNEL_DB_AUX="${BASEDIR}/db_aux"
KERNEL_DB_STATS="${BASEDIR}/db_stats"
KERNEL_DB_GREEN="${BASEDIR}/db_green"

# basedir test
test -d ${BASEDIR} || exit 0
test -f ${KERNEL_HTTP_STATS} || exit 0
test -f ${KERNEL_HTTP_AUX} || exit 0
test -f ${KERNEL_DB_AUX} || exit 0
test -f ${KERNEL_DB_STATS} || exit 0
test -f ${KERNEL_DB_GREEN} || exit 0


start() {
    ${KERNEL_DB_AUX} start
    sleep 1
    ${KERNEL_DB_STATS} start
    sleep 1
    ${KERNEL_DB_GREEN} start
    sleep 1
    ${KERNEL_HTTP_AUX} start
    sleep 1
    ${KERNEL_HTTP_STATS} start
}


stop() {
    ${KERNEL_HTTP_STATS} stop
    sleep 1
    ${KERNEL_HTTP_AUX} stop
    sleep 1
    ${KERNEL_DB_GREEN} stop
    sleep 1
    ${KERNEL_DB_STATS} stop
    sleep 1
    ${KERNEL_DB_AUX} stop
}


case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac
exit $RETVAL
