#!/bin/sh

# initial installation, after tasks
chown -R krmx:krmx /opt/kronometrix/kernel || :

if [ ! -L /etc/init.d/kkernel ]; then
    ln -s /opt/kronometrix/kernel/etc/rc/kkernel /etc/init.d/kkernel || :
fi

# link here kkernel
update-rc.d kkernel start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

if [ -d /opt/kronometrix/kernel/logs ]; then
    chown -R krmx:krmx /opt/kronometrix/kernel/logs || :
fi
/etc/init.d/kkernel start >/dev/null 2>&1 || :
